-- +goose Up
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DOMAIN CHAIN_UUID     UUID NOT NULL DEFAULT uuid_generate_v4();
CREATE DOMAIN CHAIN_CURRENCY DECIMAL(65, 0);
CREATE DOMAIN CHAIN_TIME     TIMESTAMP WITH TIME ZONE NOT NULL;
CREATE DOMAIN CHAIN_HEIGHT   INTEGER NOT NULL;

CREATE TYPE CHAIN_INTERVAL AS ENUM ('h', 'd', 'w');

-- +goose Down
DROP EXTENSION IF EXISTS "uuid-ossp";

DROP DOMAIN IF EXISTS CHAIN_UUID;
DROP DOMAIN IF EXISTS CHAIN_CURRENCY;
DROP DOMAIN IF EXISTS CHAIN_TIME;
DROP DOMAIN IF EXISTS CHAIN_HEIGHT;
DROP TYPE   IF EXISTS CHAIN_INTERVAL;